# Generated by Django 3.2.7 on 2021-09-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
